// Code generated by protoc-gen-go. DO NOT EDIT.
// source: petstore-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category             *Category `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrls            string    `protobuf:"bytes,4,opt,name=photoUrls,proto3" json:"photoUrls,omitempty"`
	Tags                 string    `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	Status               string    `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	IsDelete             bool      `protobuf:"varint,7,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37647ca434c2db, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Data) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Data) GetPhotoUrls() string {
	if m != nil {
		return m.PhotoUrls
	}
	return ""
}

func (m *Data) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Data) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Data) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type Category struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37647ca434c2db, []int{1}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37647ca434c2db, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37647ca434c2db, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37647ca434c2db, []int{4}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37647ca434c2db, []int{5}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FindRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37647ca434c2db, []int{6}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37647ca434c2db, []int{7}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindResponse) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeletesRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletesRequest) Reset()         { *m = DeletesRequest{} }
func (m *DeletesRequest) String() string { return proto.CompactTextString(m) }
func (*DeletesRequest) ProtoMessage()    {}
func (*DeletesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37647ca434c2db, []int{8}
}

func (m *DeletesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletesRequest.Unmarshal(m, b)
}
func (m *DeletesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletesRequest.Marshal(b, m, deterministic)
}
func (m *DeletesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletesRequest.Merge(m, src)
}
func (m *DeletesRequest) XXX_Size() int {
	return xxx_messageInfo_DeletesRequest.Size(m)
}
func (m *DeletesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletesRequest proto.InternalMessageInfo

func (m *DeletesRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeletesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletesResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletesResponse) Reset()         { *m = DeletesResponse{} }
func (m *DeletesResponse) String() string { return proto.CompactTextString(m) }
func (*DeletesResponse) ProtoMessage()    {}
func (*DeletesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a37647ca434c2db, []int{9}
}

func (m *DeletesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletesResponse.Unmarshal(m, b)
}
func (m *DeletesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletesResponse.Marshal(b, m, deterministic)
}
func (m *DeletesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletesResponse.Merge(m, src)
}
func (m *DeletesResponse) XXX_Size() int {
	return xxx_messageInfo_DeletesResponse.Size(m)
}
func (m *DeletesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletesResponse proto.InternalMessageInfo

func (m *DeletesResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeletesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "v1.Data")
	proto.RegisterType((*Category)(nil), "v1.Category")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "v1.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "v1.UpdateResponse")
	proto.RegisterType((*FindRequest)(nil), "v1.FindRequest")
	proto.RegisterType((*FindResponse)(nil), "v1.FindResponse")
	proto.RegisterType((*DeletesRequest)(nil), "v1.DeletesRequest")
	proto.RegisterType((*DeletesResponse)(nil), "v1.DeletesResponse")
}

func init() { proto.RegisterFile("petstore-service.proto", fileDescriptor_7a37647ca434c2db) }

var fileDescriptor_7a37647ca434c2db = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0x9d, 0x34, 0x49, 0xa7, 0xfd, 0xda, 0x7c, 0x83, 0x14, 0x59, 0x56, 0x25, 0x2c, 0xaf,
	0xa2, 0x88, 0xd8, 0x4d, 0xa8, 0x84, 0x54, 0xfe, 0x69, 0x05, 0x1b, 0x16, 0xc8, 0x55, 0x1f, 0x60,
	0x6a, 0x5f, 0x39, 0x53, 0xd2, 0x99, 0x61, 0xe6, 0x26, 0xa5, 0x42, 0x6c, 0xd8, 0xb2, 0x83, 0x1d,
	0x0f, 0xc2, 0x82, 0xd7, 0xe0, 0x15, 0x78, 0x02, 0x16, 0xac, 0x91, 0xc7, 0x76, 0x9b, 0x50, 0x8a,
	0xf8, 0x59, 0x79, 0xe6, 0xf8, 0xde, 0x73, 0xee, 0x3d, 0x77, 0x66, 0x48, 0x4f, 0x01, 0x1a, 0x94,
	0x1a, 0x86, 0x06, 0xf4, 0x9c, 0xa7, 0x10, 0x29, 0x2d, 0x51, 0x52, 0x77, 0x3e, 0xf2, 0xb7, 0x72,
	0x29, 0xf3, 0x29, 0xc4, 0x4c, 0xf1, 0x98, 0x09, 0x21, 0x91, 0x21, 0x97, 0xc2, 0x94, 0x11, 0xfe,
	0x0d, 0xfb, 0x49, 0x87, 0x39, 0x88, 0xa1, 0x39, 0x65, 0x79, 0x0e, 0x3a, 0x96, 0xca, 0x46, 0x5c,
	0x8e, 0x0e, 0x3f, 0x39, 0xa4, 0xb9, 0xcf, 0x90, 0xd1, 0x0d, 0xe2, 0xf2, 0xcc, 0x73, 0x02, 0xa7,
	0xbf, 0x9a, 0xb8, 0x3c, 0xa3, 0x7d, 0xd2, 0x49, 0x19, 0x42, 0x2e, 0xf5, 0x99, 0xe7, 0x06, 0x4e,
	0x7f, 0x6d, 0xbc, 0x1e, 0xcd, 0x47, 0xd1, 0x5e, 0x85, 0x25, 0xe7, 0x7f, 0x29, 0x25, 0x4d, 0xc1,
	0x4e, 0xc0, 0x6b, 0xd8, 0x5c, 0xbb, 0xa6, 0x5b, 0x64, 0x55, 0x4d, 0x24, 0xca, 0x43, 0x3d, 0x35,
	0x5e, 0xd3, 0xfe, 0xb8, 0x00, 0x8a, 0x0c, 0x64, 0xb9, 0xf1, 0x56, 0xca, 0x8c, 0x62, 0x4d, 0x7b,
	0xa4, 0x65, 0x90, 0xe1, 0xcc, 0x78, 0x2d, 0x8b, 0x56, 0x3b, 0xea, 0x93, 0x0e, 0x37, 0xfb, 0x30,
	0x05, 0x04, 0xaf, 0x1d, 0x38, 0xfd, 0x4e, 0x72, 0xbe, 0x0f, 0x23, 0xd2, 0xa9, 0xeb, 0x59, 0xa8,
	0x7f, 0xc5, 0xd6, 0x5f, 0x57, 0xe5, 0x5e, 0x54, 0x15, 0xde, 0x27, 0xff, 0xed, 0x69, 0x60, 0x08,
	0x09, 0xbc, 0x98, 0x81, 0x41, 0xda, 0x25, 0x0d, 0xa6, 0x78, 0xd5, 0x75, 0xb1, 0xa4, 0x5b, 0xa4,
	0x99, 0x31, 0x64, 0x55, 0xcb, 0x9d, 0xa2, 0xe5, 0xc2, 0x9e, 0xc4, 0xa2, 0xe1, 0x1d, 0xb2, 0x51,
	0x13, 0x18, 0x25, 0x85, 0x81, 0x9f, 0x30, 0x78, 0xa4, 0x7d, 0x02, 0xc6, 0xb0, 0xbc, 0xd6, 0xae,
	0xb7, 0x85, 0xfc, 0xa1, 0xca, 0xfe, 0x4d, 0xbe, 0x26, 0xf8, 0x0b, 0xf9, 0x98, 0xac, 0x3d, 0xe6,
	0x22, 0xbb, 0x5a, 0xbc, 0xb4, 0xd0, 0xad, 0x8f, 0x40, 0x78, 0x8f, 0xac, 0x97, 0x09, 0x57, 0x8a,
	0xfd, 0xba, 0xdc, 0x31, 0xd9, 0x28, 0x07, 0x65, 0x7e, 0x5f, 0xf3, 0x2e, 0xd9, 0x3c, 0xcf, 0xf9,
	0xf3, 0x1e, 0xc7, 0x1f, 0x5d, 0xb2, 0xf9, 0x0c, 0xf0, 0xa0, 0xb8, 0x39, 0x07, 0xe5, 0xc5, 0xa1,
	0x4f, 0x48, 0xab, 0x1c, 0x1a, 0xfd, 0xdf, 0x9e, 0xe0, 0xc5, 0x13, 0xe0, 0xd3, 0x45, 0xa8, 0x14,
	0x0c, 0x7b, 0x6f, 0x3e, 0x7f, 0x79, 0xef, 0x76, 0xc3, 0x35, 0x7b, 0xc3, 0xe6, 0xa3, 0x58, 0x01,
	0xee, 0x3a, 0x83, 0x82, 0xa8, 0xb4, 0xbf, 0x24, 0x5a, 0x9a, 0x65, 0x49, 0xb4, 0x3c, 0x9d, 0x9a,
	0xc8, 0xff, 0x91, 0x68, 0x8f, 0x34, 0x0b, 0x63, 0xe9, 0x66, 0x91, 0xb3, 0x30, 0x13, 0xbf, 0x7b,
	0x01, 0x54, 0x14, 0x9e, 0xa5, 0xa0, 0xb4, 0xbb, 0x40, 0x11, 0xbf, 0xe2, 0xd9, 0x6b, 0xfa, 0x94,
	0xb4, 0x2b, 0xa7, 0xa8, 0xd5, 0x5e, 0xb6, 0xda, 0xbf, 0xb6, 0x84, 0x2d, 0xb3, 0x0d, 0x2e, 0xb1,
	0x3d, 0xfa, 0xe6, 0xbc, 0x7b, 0xf8, 0xd5, 0xa1, 0x6f, 0x1d, 0xd2, 0xad, 0xfd, 0x0b, 0x2a, 0x03,
	0x43, 0x4d, 0xae, 0xe7, 0x72, 0x98, 0x6b, 0x95, 0x0e, 0x73, 0x86, 0x70, 0xca, 0xce, 0x86, 0x38,
	0x43, 0xa9, 0x39, 0x0b, 0x94, 0x96, 0xc7, 0x90, 0x22, 0xbd, 0x35, 0x41, 0x54, 0x66, 0x37, 0x8e,
	0x73, 0x8e, 0x93, 0xd9, 0x51, 0x94, 0xca, 0x93, 0x18, 0x01, 0x34, 0x33, 0xec, 0xb9, 0xd0, 0x18,
	0x5f, 0x91, 0x3f, 0xf5, 0x7b, 0x75, 0x54, 0x24, 0x1e, 0xc0, 0x4b, 0x6e, 0x90, 0x8b, 0x3c, 0x4a,
	0xe5, 0xb8, 0x31, 0x8a, 0xb6, 0x07, 0x8e, 0x33, 0xee, 0x32, 0xa5, 0xa6, 0x3c, 0xb5, 0x6f, 0x56,
	0x7c, 0x6c, 0xa4, 0xd8, 0xbd, 0x84, 0x24, 0xb7, 0x49, 0x63, 0x67, 0x7b, 0x87, 0xee, 0x90, 0x41,
	0x02, 0x38, 0xd3, 0x02, 0xb2, 0xe0, 0x74, 0x02, 0x22, 0xc0, 0x09, 0x04, 0x1a, 0x8c, 0x9c, 0xe9,
	0x14, 0x82, 0x4c, 0x82, 0x09, 0x84, 0xc4, 0xc0, 0xaa, 0x44, 0xb4, 0x45, 0x9a, 0x1f, 0x5c, 0xa7,
	0x7d, 0xd4, 0xb2, 0xef, 0xe0, 0xcd, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x50, 0x21, 0x65,
	0x71, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PetStoreServiceClient is the client API for PetStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PetStoreServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	Deletes(ctx context.Context, in *DeletesRequest, opts ...grpc.CallOption) (*DeletesResponse, error)
}

type petStoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewPetStoreServiceClient(cc *grpc.ClientConn) PetStoreServiceClient {
	return &petStoreServiceClient{cc}
}

func (c *petStoreServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.PetStoreService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *petStoreServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/v1.PetStoreService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *petStoreServiceClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/v1.PetStoreService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *petStoreServiceClient) Deletes(ctx context.Context, in *DeletesRequest, opts ...grpc.CallOption) (*DeletesResponse, error) {
	out := new(DeletesResponse)
	err := c.cc.Invoke(ctx, "/v1.PetStoreService/Deletes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PetStoreServiceServer is the server API for PetStoreService service.
type PetStoreServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Find(context.Context, *FindRequest) (*FindResponse, error)
	Deletes(context.Context, *DeletesRequest) (*DeletesResponse, error)
}

// UnimplementedPetStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPetStoreServiceServer struct {
}

func (*UnimplementedPetStoreServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedPetStoreServiceServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedPetStoreServiceServer) Find(ctx context.Context, req *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (*UnimplementedPetStoreServiceServer) Deletes(ctx context.Context, req *DeletesRequest) (*DeletesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deletes not implemented")
}

func RegisterPetStoreServiceServer(s *grpc.Server, srv PetStoreServiceServer) {
	s.RegisterService(&_PetStoreService_serviceDesc, srv)
}

func _PetStoreService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetStoreServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PetStoreService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetStoreServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PetStoreService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetStoreServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PetStoreService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetStoreServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PetStoreService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetStoreServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PetStoreService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetStoreServiceServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PetStoreService_Deletes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetStoreServiceServer).Deletes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PetStoreService/Deletes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetStoreServiceServer).Deletes(ctx, req.(*DeletesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PetStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PetStoreService",
	HandlerType: (*PetStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PetStoreService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PetStoreService_Update_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _PetStoreService_Find_Handler,
		},
		{
			MethodName: "Deletes",
			Handler:    _PetStoreService_Deletes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "petstore-service.proto",
}
